import os
from datetime import datetime
from pathlib import Path
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table,
    TableStyle, HRFlowable, PageBreak, KeepTogether
)
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY

from promptheus.scorer import PostureReport, CategoryScore

PW = A4[0]
PH = A4[1]

# Colors
RED   = colors.HexColor("#C0392B")
DARK  = colors.HexColor("#1a1a2e")
GREY  = colors.HexColor("#2d2d2d")
LGREY = colors.HexColor("#f5f5f5")
MGREY = colors.HexColor("#dddddd")
BLUE  = colors.HexColor("#2980B9")
TEAL  = colors.HexColor("#16a085")
AMBER = colors.HexColor("#d35400")
GREEN = colors.HexColor("#1e8449")
WHITE = colors.white


def _S(name, **kw):
    return ParagraphStyle(name, **kw)


def _make_styles():
    h1   = _S("H1", fontSize=18, textColor=RED, leading=24,
               fontName="Helvetica-Bold", spaceAfter=6, spaceBefore=12)
    h2   = _S("H2", fontSize=12, textColor=DARK, leading=16,
               fontName="Helvetica-Bold", spaceAfter=4, spaceBefore=8)
    body = _S("BD", fontSize=10, textColor=GREY, leading=15,
               fontName="Helvetica", spaceAfter=4, alignment=TA_JUSTIFY)
    note = _S("NO", fontSize=9, textColor=BLUE, leading=13,
               fontName="Helvetica-Oblique", leftIndent=10, spaceAfter=4)
    code = _S("CO", fontSize=8.5, textColor=RED, fontName="Courier",
               leading=13, leftIndent=10, spaceAfter=3)
    return h1, h2, body, note, code


def _HR():
    return HRFlowable(
        width="100%", thickness=0.5,
        color=MGREY, spaceAfter=6, spaceBefore=6
    )


def _SP(n=8):
    return Spacer(1, n)


def _on_page(canvas, doc):
    canvas.saveState()
    pw, ph = A4
    canvas.setFillColor(DARK)
    canvas.rect(0, ph - 1.1*cm, pw, 1.1*cm, fill=1, stroke=0)
    canvas.setFont("Helvetica-Bold", 8)
    canvas.setFillColor(WHITE)
    canvas.drawString(2*cm, ph - 0.78*cm, "PROMPTHEUS — LLM Security Assessment Report")
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor("#aaaaaa"))
    canvas.drawRightString(pw - 2*cm, ph - 0.78*cm, "Confidential")
    canvas.setFillColor(LGREY)
    canvas.rect(0, 0, pw, 0.9*cm, fill=1, stroke=0)
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor("#777777"))
    canvas.drawString(2*cm, 0.32*cm, "Generated by PROMPTHEUS — For authorized use only")
    canvas.drawRightString(pw - 2*cm, 0.32*cm, f"Page {doc.page}")
    canvas.restoreState()


def _first_page(canvas, doc):
    canvas.saveState()
    pw, ph = A4
    canvas.setFillColor(DARK)
    canvas.rect(0, 0, pw, ph, fill=1, stroke=0)
    canvas.setFillColor(RED)
    canvas.rect(0, ph - 0.5*cm, pw, 0.5*cm, fill=1, stroke=0)
    canvas.setStrokeColor(colors.HexColor("#2a2a4a"))
    canvas.setLineWidth(0.4)
    for y in range(0, int(ph), 35):
        canvas.line(0, y, pw, y)
    canvas.restoreState()


def _risk_color(score: float):
    if score >= 7:
        return RED
    elif score >= 4:
        return AMBER
    else:
        return GREEN


def _overall_color(score: float):
    if score >= 80:
        return GREEN
    elif score >= 60:
        return AMBER
    elif score >= 40:
        return colors.HexColor("#d35400")
    else:
        return RED


def generate_report(report: PostureReport,
                    target_url: str = "http://localhost:5000",
                    output_path: str = None) -> str:
    if output_path is None:
        output_dir = Path("reports")
        output_dir.mkdir(exist_ok=True)
        timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
        output_path = str(output_dir / f"promptheus_report_{timestamp}.pdf")

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=2*cm,
        leftMargin=2*cm,
        topMargin=2.2*cm,
        bottomMargin=1.8*cm
    )

    h1, h2, body, note, code = _make_styles()
    story = []

    # ── COVER PAGE ─────────────────────────────────────────────────────────
    cover_title = _S("CT", fontSize=30, textColor=WHITE,
                      leading=38, alignment=TA_CENTER,
                      fontName="Helvetica-Bold")
    cover_sub   = _S("CS", fontSize=12, textColor=colors.HexColor("#cccccc"),
                      leading=18, alignment=TA_CENTER, fontName="Helvetica")
    cover_score = _S("CSC", fontSize=48, textColor=_overall_color(report.overall_score),
                      leading=56, alignment=TA_CENTER, fontName="Helvetica-Bold")
    cover_risk  = _S("CR", fontSize=16,
                      textColor=_overall_color(report.overall_score),
                      leading=22, alignment=TA_CENTER, fontName="Helvetica-Bold")

    story.append(_SP(100))
    story.append(Paragraph("PROMPTHEUS", cover_title))
    story.append(_SP(6))
    story.append(Paragraph("LLM Security Assessment Report", cover_sub))
    story.append(_SP(40))
    story.append(Paragraph(f"{report.overall_score}", cover_score))
    story.append(Paragraph("out of 100", cover_sub))
    story.append(_SP(8))
    story.append(Paragraph(f"{report.risk_level} RISK", cover_risk))
    story.append(_SP(40))

    meta = [
        ["Target", target_url],
        ["Scan date", report.scan_timestamp or datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")],
        ["Total attacks", str(report.total_attacks)],
        ["Framework", "OWASP LLM Top 10"],
    ]
    mt = Table(meta, colWidths=[4*cm, 10*cm])
    mt.setStyle(TableStyle([
        ("FONTNAME",      (0,0),(0,-1), "Helvetica-Bold"),
        ("FONTNAME",      (1,0),(1,-1), "Helvetica"),
        ("FONTSIZE",      (0,0),(-1,-1), 9),
        ("TEXTCOLOR",     (0,0),(0,-1), colors.HexColor("#aaaaaa")),
        ("TEXTCOLOR",     (1,0),(1,-1), WHITE),
        ("TOPPADDING",    (0,0),(-1,-1), 5),
        ("BOTTOMPADDING", (0,0),(-1,-1), 5),
        ("LEFTPADDING",   (0,0),(-1,-1), 8),
        ("LINEBELOW",     (0,0),(-1,-2), 0.3, colors.HexColor("#333355")),
    ]))
    story.append(mt)
    story.append(PageBreak())

    # ── EXECUTIVE SUMMARY ──────────────────────────────────────────────────
    story.append(Paragraph("Executive Summary", h1))
    story.append(_HR())

    risk_desc = {
        "LOW":      "The target application demonstrates strong resistance to LLM-specific attacks. Minor issues were identified but pose limited risk.",
        "MEDIUM":   "The target application has moderate security gaps. Several attacks partially succeeded, indicating areas requiring attention.",
        "HIGH":     "The target application has significant security vulnerabilities. Multiple attacks succeeded, posing real risk of data exposure.",
        "CRITICAL": "The target application is critically vulnerable. Multiple high-severity attacks succeeded, indicating immediate remediation is required.",
    }.get(report.risk_level, "")

    story.append(Paragraph(
        f"PROMPTHEUS conducted an automated LLM security assessment against {target_url} "
        f"using {report.total_attacks} attack payloads across {len(report.category_scores)} "
        f"OWASP LLM Top 10 categories. The application received an overall posture score of "
        f"{report.overall_score}/100, corresponding to a {report.risk_level} risk rating. "
        f"{risk_desc}",
        body
    ))
    story.append(_SP())

    # Summary stats table
    stats = [
        ["Metric", "Count", "Percentage"],
        ["Attacks fired",    str(report.total_attacks),  "100%"],
        ["Successful attacks", str(report.total_success),
         f"{report.total_success/max(report.total_attacks,1)*100:.0f}%"],
        ["Partial successes", str(report.total_partial),
         f"{report.total_partial/max(report.total_attacks,1)*100:.0f}%"],
        ["Failed attacks",   str(report.total_failure),
         f"{report.total_failure/max(report.total_attacks,1)*100:.0f}%"],
        ["Critical findings", str(len(report.critical_findings)), "—"],
    ]
    st = Table(stats, colWidths=[8*cm, 4*cm, 5.5*cm])
    st.setStyle(TableStyle([
        ("BACKGROUND",    (0,0),(-1,0),  DARK),
        ("TEXTCOLOR",     (0,0),(-1,0),  WHITE),
        ("FONTNAME",      (0,0),(-1,0),  "Helvetica-Bold"),
        ("FONTSIZE",      (0,0),(-1,-1), 9),
        ("FONTNAME",      (0,1),(-1,-1), "Helvetica"),
        ("ROWBACKGROUNDS",(0,1),(-1,-1), [WHITE, LGREY]),
        ("GRID",          (0,0),(-1,-1), 0.4, MGREY),
        ("TOPPADDING",    (0,0),(-1,-1), 5),
        ("BOTTOMPADDING", (0,0),(-1,-1), 5),
        ("LEFTPADDING",   (0,0),(-1,-1), 8),
        ("TEXTCOLOR",     (1,2),(1,2),   RED),
        ("FONTNAME",      (1,2),(1,2),   "Helvetica-Bold"),
    ]))
    story.append(st)
    story.append(_SP(12))

    # ── CATEGORY BREAKDOWN ─────────────────────────────────────────────────
    story.append(Paragraph("OWASP LLM Top 10 — Category Breakdown", h1))
    story.append(_HR())
    story.append(Paragraph(
        "Each category below shows the risk score (0 = secure, 10 = fully compromised), "
        "test counts, and individual findings with AI judge evidence.",
        body
    ))
    story.append(_SP())

    for cat_id, cs in sorted(report.category_scores.items()):
        rc = _risk_color(cs.risk_score)
        block = []

        # Category header
        hdr = [[
            Paragraph(cat_id, _S(f"ch{cat_id}", fontSize=11, textColor=WHITE,
                                  fontName="Helvetica-Bold", alignment=TA_CENTER)),
            Paragraph(cs.category_name, _S(f"cn{cat_id}", fontSize=11,
                                            textColor=WHITE, fontName="Helvetica-Bold")),
            Paragraph(f"Risk: {cs.risk_score:.1f}/10",
                      _S(f"cr{cat_id}", fontSize=11, textColor=WHITE,
                         fontName="Helvetica-Bold", alignment=TA_CENTER)),
        ]]
        ht = Table(hdr, colWidths=[2*cm, 11*cm, 4.5*cm])
        ht.setStyle(TableStyle([
            ("BACKGROUND",    (0,0),(-1,-1), rc),
            ("TOPPADDING",    (0,0),(-1,-1), 7),
            ("BOTTOMPADDING", (0,0),(-1,-1), 7),
            ("LEFTPADDING",   (0,0),(-1,-1), 8),
        ]))
        block.append(ht)

        # Test counts
        counts = [[
            Paragraph(f"Tests: {cs.total_tests}", _S("tc", fontSize=9,
                      textColor=GREY, fontName="Helvetica")),
            Paragraph(f"Success: {cs.successes}", _S("tcs", fontSize=9,
                      textColor=RED, fontName="Helvetica-Bold")),
            Paragraph(f"Partial: {cs.partials}", _S("tcp", fontSize=9,
                      textColor=AMBER, fontName="Helvetica-Bold")),
            Paragraph(f"Failure: {cs.failures}", _S("tcf", fontSize=9,
                      textColor=GREEN, fontName="Helvetica-Bold")),
        ]]
        ct = Table(counts, colWidths=[4.375*cm]*4)
        ct.setStyle(TableStyle([
            ("BACKGROUND",    (0,0),(-1,-1), LGREY),
            ("TOPPADDING",    (0,0),(-1,-1), 5),
            ("BOTTOMPADDING", (0,0),(-1,-1), 5),
            ("LEFTPADDING",   (0,0),(-1,-1), 8),
            ("GRID",          (0,0),(-1,-1), 0.3, MGREY),
        ]))
        block.append(ct)

        # Individual findings
        if cs.findings:
            for f in cs.findings:
                verdict_color = RED if f.judge_verdict == "success" else AMBER
                conf = f"{f.judge_confidence:.2f}" if f.judge_confidence else "—"
                evidence = (f.judge_evidence or "")[:120]
                notes    = (f.judge_notes    or "")[:100]

                fd = [[
                    Paragraph(f.payload_id, _S("fid", fontSize=8.5,
                              textColor=verdict_color, fontName="Courier-Bold")),
                    Paragraph(f.name[:35], _S("fn", fontSize=8.5,
                              textColor=GREY, fontName="Helvetica-Bold")),
                    Paragraph(f.judge_verdict.upper() if f.judge_verdict else "—",
                              _S("fv", fontSize=8.5, textColor=verdict_color,
                                 fontName="Helvetica-Bold", alignment=TA_CENTER)),
                    Paragraph(conf, _S("fc", fontSize=8.5,
                              textColor=GREY, fontName="Helvetica",
                              alignment=TA_CENTER)),
                ]]
                ft = Table(fd, colWidths=[2.2*cm, 8.3*cm, 3*cm, 2*cm])
                ft.setStyle(TableStyle([
                    ("BACKGROUND",    (0,0),(-1,-1), WHITE),
                    ("GRID",          (0,0),(-1,-1), 0.3, MGREY),
                    ("TOPPADDING",    (0,0),(-1,-1), 4),
                    ("BOTTOMPADDING", (0,0),(-1,-1), 4),
                    ("LEFTPADDING",   (0,0),(-1,-1), 6),
                    ("VALIGN",        (0,0),(-1,-1), "TOP"),
                ]))
                block.append(ft)

                if evidence:
                    ev_row = [[
                        Paragraph("Evidence:", _S("el", fontSize=8,
                                  textColor=colors.HexColor("#888888"),
                                  fontName="Helvetica-Bold")),
                        Paragraph(evidence, _S("ev", fontSize=8,
                                  textColor=GREY, fontName="Helvetica-Oblique")),
                    ]]
                    et = Table(ev_row, colWidths=[2.2*cm, 13.3*cm])
                    et.setStyle(TableStyle([
                        ("BACKGROUND",    (0,0),(-1,-1),
                         colors.HexColor("#fff9f9")),
                        ("TOPPADDING",    (0,0),(-1,-1), 3),
                        ("BOTTOMPADDING", (0,0),(-1,-1), 3),
                        ("LEFTPADDING",   (0,0),(-1,-1), 6),
                        ("LINEBELOW",     (0,0),(-1,-1), 0.3, MGREY),
                    ]))
                    block.append(et)
        else:
            no_find = [[Paragraph(
                "No successful or partial findings in this category.",
                _S("nf", fontSize=9, textColor=GREEN,
                   fontName="Helvetica-Oblique")
            )]]
            nft = Table(no_find, colWidths=[17.5*cm])
            nft.setStyle(TableStyle([
                ("BACKGROUND",    (0,0),(-1,-1), colors.HexColor("#eafaf1")),
                ("TOPPADDING",    (0,0),(-1,-1), 6),
                ("BOTTOMPADDING", (0,0),(-1,-1), 6),
                ("LEFTPADDING",   (0,0),(-1,-1), 10),
            ]))
            block.append(nft)

        block.append(_SP(10))
        story.append(KeepTogether(block[:3]))
        story.extend(block[3:])

    # ── CRITICAL FINDINGS ──────────────────────────────────────────────────
    if report.critical_findings:
        story.append(PageBreak())
        story.append(Paragraph("Critical Findings — Immediate Action Required", h1))
        story.append(_HR())
        story.append(Paragraph(
            "The following critical-severity attacks fully succeeded. "
            "These represent the highest-priority remediation items.",
            body
        ))
        story.append(_SP())

        for i, f in enumerate(report.critical_findings, 1):
            block = []
            block.append(Paragraph(
                f"{i}. {f.name} ({f.payload_id})",
                _S(f"cfh{i}", fontSize=11, textColor=RED,
                   fontName="Helvetica-Bold", spaceBefore=8, spaceAfter=4)
            ))
            details = [
                ["Category",    f"{f.category} — {f.subcategory}"],
                ["Attack goal", f.attack_goal],
                ["Payload",     f.prompt[:150] + ("..." if len(f.prompt) > 150 else "")],
                ["Evidence",    f.judge_evidence or "—"],
                ["Notes",       f.judge_notes    or "—"],
            ]
            dt = Table(details, colWidths=[3*cm, 14.5*cm])
            dt.setStyle(TableStyle([
                ("BACKGROUND",    (0,0),(0,-1), LGREY),
                ("FONTNAME",      (0,0),(0,-1), "Helvetica-Bold"),
                ("FONTSIZE",      (0,0),(-1,-1), 8.5),
                ("FONTNAME",      (1,0),(1,-1), "Helvetica"),
                ("ROWBACKGROUNDS",(1,0),(1,-1), [WHITE, colors.HexColor("#fff5f5")]),
                ("GRID",          (0,0),(-1,-1), 0.3, MGREY),
                ("TOPPADDING",    (0,0),(-1,-1), 5),
                ("BOTTOMPADDING", (0,0),(-1,-1), 5),
                ("LEFTPADDING",   (0,0),(-1,-1), 7),
                ("VALIGN",        (0,0),(-1,-1), "TOP"),
                ("TEXTCOLOR",     (0,0),(0,-1), GREY),
            ]))
            block.append(dt)
            block.append(_SP(8))
            story.append(KeepTogether(block))

    # ── RECOMMENDATIONS ────────────────────────────────────────────────────
    story.append(PageBreak())
    story.append(Paragraph("Recommendations", h1))
    story.append(_HR())

    recs = [
        ("LLM01 — Prompt Injection", RED,
         "Implement input validation to detect and reject injection patterns. "
         "Use a separate non-injectable channel for system instructions. "
         "Consider a prompt firewall or guardrails layer before the LLM."),
        ("LLM06 — Sensitive Data Disclosure", AMBER,
         "Never store secrets, credentials, or PII in the system prompt. "
         "Use a secrets manager (AWS Secrets Manager, HashiCorp Vault) for runtime injection. "
         "Audit all system prompt content for sensitive information."),
        ("LLM08 — Excessive Agency", RED,
         "Apply least-privilege to all agent tools. "
         "Implement strict recipient allowlists for email tools. "
         "Require human approval for high-impact actions. "
         "Log and alert on all tool invocations."),
        ("RAG Security", TEAL,
         "Sanitize all documents before adding to the vector store. "
         "Implement trust levels — never inject untrusted content directly into system context. "
         "Use a separate prompt structure that clearly delimits retrieved content from instructions."),
        ("Output Handling", BLUE,
         "Never render LLM output as raw HTML. "
         "Use textContent instead of innerHTML in frontend code. "
         "Apply a strict HTML sanitizer (DOMPurify) if rich text rendering is required."),
    ]

    for title, color, rec in recs:
        block = KeepTogether([
            Paragraph(title, _S(f"rh{title[:4]}", fontSize=11, textColor=color,
                                 fontName="Helvetica-Bold",
                                 spaceBefore=10, spaceAfter=4)),
            Paragraph(rec, body),
            _SP(4),
            _HR(),
        ])
        story.append(block)

    # ── FOOTER NOTE ────────────────────────────────────────────────────────
    story.append(_SP(16))
    footer_data = [[Paragraph(
        "This report was generated automatically by PROMPTHEUS, an open-source LLM "
        "red-teaming framework. Findings should be validated by a qualified security "
        "engineer before remediation. This report is confidential and intended for "
        "authorized recipients only.",
        _S("fn", fontSize=8.5, textColor=colors.HexColor("#777777"),
           fontName="Helvetica-Oblique", leading=13)
    )]]
    ft = Table(footer_data, colWidths=[17.5*cm])
    ft.setStyle(TableStyle([
        ("BACKGROUND",    (0,0),(-1,-1), LGREY),
        ("BOX",           (0,0),(-1,-1), 0.5, MGREY),
        ("TOPPADDING",    (0,0),(-1,-1), 10),
        ("BOTTOMPADDING", (0,0),(-1,-1), 10),
        ("LEFTPADDING",   (0,0),(-1,-1), 12),
        ("RIGHTPADDING",  (0,0),(-1,-1), 12),
    ]))
    story.append(ft)

    doc.build(story, onFirstPage=_first_page, onLaterPages=_on_page)
    return output_path